// Package static holds the browser assets the binary serves, embedded so the
// image stays a single self-contained artefact with nothing to fetch at runtime.
//
// datastar.js is the Datastar BROWSER RUNTIME at v1.0.2, vendored from
// https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.2/bundles/datastar.js
//
// The Go SDK this project imports is starfederation/datastar-go v1.2.2. Those are
// two different version lines and both are correct — do not "align" them
// (research D-33). npm is not the distribution channel for this bundle; the
// GitHub tag is (specs/research/frontend.md, Trap 2).
package static

import "embed"

// FS carries every asset served under /static. app.css is generated by the
// Tailwind step and is gitignored, so it is absent from a clean checkout —
// hence the `all:` prefix is not used and the pattern tolerates its absence
// only after `task gen` has run.
//
//go:embed datastar.js
var FS embed.FS

// Datastar is the vendored browser runtime. Handlers serve it directly rather
// than reading through FS so a missing asset fails at init, not on first request.
var Datastar = mustRead("datastar.js")

func mustRead(name string) []byte {
	b, err := FS.ReadFile(name)
	if err != nil {
		// This can only fire if the embed pattern and the file disagree, which is
		// a build-time mistake, not a runtime condition.
		panic("static: " + err.Error())
	}
	return b
}
