package identity

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/pocketbase/pocketbase/core"

	"medikube/internal/domain"
	domainidentity "medikube/internal/domain/identity"
	service "medikube/internal/service/identity"
	"medikube/internal/store"
)

// Repository is the account repository the identity service declares, against
// PocketBase.
//
// It stores and reads; it decides nothing. Whether an account may sign in, who
// may change what and what a refusal is allowed to say are all the service's,
// which is why a disabled account authenticates here and is refused above: an
// adapter that refused it would make the service's own check unreachable and
// the test of that check vacuous.
type Repository struct {
	app core.App
}

// The seam this package exists to fill. A compile-time assertion rather than a
// runtime one: a method that drifts from the port should not build.
var _ service.Repository = (*Repository)(nil)

func NewRepository(app core.App) (*Repository, error) {
	if app == nil {
		return nil, errors.New("identity: the account repository is wired with no application")
	}

	return &Repository{app: app}, nil
}

// Create stores the account and its first credential in one save.
//
// One save and not two, which is FR-003's "no partially created account"
// expressed as the only shape that can have it: an account written by one
// statement and given a password by another is an account with no way into it
// if the second fails.
//
// It writes neither the confirmation nor a token key. `verified` is absent from
// store.UserToRecord by design, so a registration that asked to arrive already
// confirmed cannot — there is no line here that could honour it (FR-075). The
// token key is PocketBase's autogenerated column.
func (r *Repository) Create(
	ctx context.Context,
	draft domainidentity.User,
	password string,
) (domainidentity.User, error) {
	collection, err := accounts(r.app)
	if err != nil {
		return domainidentity.User{}, err
	}

	record := core.NewRecord(collection)

	if mapErr := store.UserToRecord(record, draft); mapErr != nil {
		return domainidentity.User{}, mapErr
	}

	// The mapper deliberately writes neither the address nor the credential
	// (research D-13): the address is the one thing FR-011 does not let a
	// person change about themselves, and the credential is PocketBase's.
	// Registration is the single moment both are set, and this is the single
	// place that sets them.
	record.SetEmail(draft.Email)
	record.SetPassword(password)

	if saveErr := r.app.SaveWithContext(ctx, record); saveErr != nil {
		return domainidentity.User{}, writeFailure("creating an account", saveErr)
	}

	return store.UserFromRecord(record)
}

func (r *Repository) Get(ctx context.Context, id string) (domainidentity.User, error) {
	record, err := byID(ctx, r.app, id)
	if err != nil {
		return domainidentity.User{}, err
	}

	return store.UserFromRecord(record)
}

// FindByEmail resolves an address case-insensitively, which is what makes
// Amara@… and amara@… one account (FR-003).
//
// It does NOT go through app.FindAuthRecordByEmail. That call is
// case-insensitive only when the single-column unique index on `email` carries
// COLLATE NOCASE, and PocketBase's stock index does not; MediKube's
// idx_users_email_lower is on LOWER(email), which dbutils does not recognise as
// an index on `email` at all. Measured against v0.40.1: FindAuthRecordByEmail
// answers "no rows" for AMARA@… against an account stored as amara@…. Reading
// the address that way would make every other spelling a second account, and
// the unique index would then be the only thing refusing it — at the storage
// layer, as a 500.
func (r *Repository) FindByEmail(ctx context.Context, email string) (domainidentity.User, error) {
	record, err := byEmail(ctx, r.app, email)
	if err != nil {
		return domainidentity.User{}, err
	}

	return store.UserFromRecord(record)
}

// Update writes the account as supplied.
//
// It writes what it is given rather than deciding which members a caller may
// move: a repository that made that decision would be a second authorization
// rule in the layer that is meant to have none. The service reads the stored
// account first and carries the address, the role and the disabled instant over
// from it, and its own test is what proves that step is there.
func (r *Repository) Update(ctx context.Context, user domainidentity.User) (domainidentity.User, error) {
	record, err := byID(ctx, r.app, user.ID)
	if err != nil {
		return domainidentity.User{}, err
	}

	if mapErr := store.UserToRecord(record, user); mapErr != nil {
		return domainidentity.User{}, mapErr
	}

	// The confirmation, and the one column outside the profile an update
	// writes. store.UserToRecord refuses to write it — mapping_test.go asserts
	// that directly — so that no profile patch can confirm an address by
	// carrying the field. Confirming happens through exactly one service
	// operation, and this is where it lands (FR-075).
	//
	// It is not a credential change and must not rotate the token key: a person
	// who confirms their address from a link on their phone must not be signed
	// out of their laptop for it.
	record.SetVerified(user.EmailConfirmed)

	if saveErr := r.app.SaveWithContext(ctx, record); saveErr != nil {
		return domainidentity.User{}, writeFailure("updating an account", saveErr)
	}

	return store.UserFromRecord(record)
}

// Delete removes the account permanently (FR-014).
//
// Every medication recorded under it goes with it, by the CascadeDelete on
// `medications.owner`; the audit trail does not, by the deliberate absence of
// one on `audit_events.actor` — PocketBase unsets that relation and re-saves
// the row instead, so the account_delete row outlives the account with its
// actor emptied and `actor_kind` as the surviving evidence that a person did it
// (research D-22, defect D17).
func (r *Repository) Delete(ctx context.Context, id string) error {
	record, err := byID(ctx, r.app, id)
	if err != nil {
		return err
	}

	if deleteErr := r.app.DeleteWithContext(ctx, record); deleteErr != nil {
		return writeFailure("deleting an account", deleteErr)
	}

	return nil
}

// accountSchema is the query surface every read in this package is built
// against, resolved once: it is a value with no instance state in it.
var accountSchema = store.AccountSchema()

// accounts is the collection every method in this package reads.
func accounts(app core.App) (*core.Collection, error) {
	collection, err := app.FindCachedCollectionByNameOrId(store.AccountCollection)
	if err != nil {
		return nil, fmt.Errorf("identity: reading the %s collection: %w", store.AccountCollection, err)
	}

	return collection, nil
}

// byID reads one account, with the context, which is why it is not
// app.FindRecordById: that call takes none, so a cancelled request would run
// the statement to completion anyway.
func byID(ctx context.Context, app core.App, id string) (*core.Record, error) {
	return one(ctx, app, "reading an account", store.Equal(store.ColumnID, id))
}

// byEmail reads one account by its address, case-insensitively — FR-003's
// comparison, expressed through internal/store's builder so that the fold and
// the LOWER(email) expression it has to match stay in the one package that
// owns both.
func byEmail(ctx context.Context, app core.App, email string) (*core.Record, error) {
	return one(ctx, app, "reading the account for an address", store.SameAddress(email))
}

// one runs a narrowing that identifies at most one account.
//
// It goes through the typed builder rather than through a filter or a
// hand-written expression, for the same reason internal/store/medication does:
// a query language assembled at a call site is the one place a value is
// interpolated into a query text rather than bound to it, and internal/store is
// where that stops.
func one(
	ctx context.Context,
	app core.App,
	doing string,
	conditions ...store.Condition,
) (*core.Record, error) {
	collection, err := accounts(app)
	if err != nil {
		return nil, err
	}

	built, err := accountSchema.Build(store.Query{Conditions: conditions, Limit: 1})
	if err != nil {
		return nil, err
	}

	record := &core.Record{}

	if queryErr := built.Apply(app.RecordQuery(collection)).
		WithContext(ctx).
		One(record); queryErr != nil {
		return nil, readFailure(doing, queryErr)
	}

	return record, nil
}

// readFailure separates "there is no such row" from "I could not find out", and
// only the first is a refusal.
//
// The second must never become domain.ErrNotFound. A dropped connection, a
// cancelled request or a locked database reported as "no such account" is a
// failure that reads as an answer: the service would report a 404 for an
// account that exists, and — on the sign-in path — a refusal for a credential
// nobody checked. sql.ErrNoRows is what dbx returns for an empty result set
// (dbx/rows.go:244) and it is the only miss.
func readFailure(doing string, err error) error {
	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("identity: %s: %w", doing, domain.ErrNotFound)
	}

	return fmt.Errorf("identity: %s: %w", doing, err)
}

// writeFailure maps a unique-index violation onto domain.ErrConflict.
//
// The index is the enforcement and this is only the translation: SQLite reports
// `UNIQUE constraint failed: index 'idx_users_email_lower'`, which
// PocketBase's own NormalizeUniqueIndexError leaves untouched because the
// message names an index rather than a `users.email` column. Without this the
// second registration of one address reaches the client as a 500.
//
// Every unique index on the collection is an address — PocketBase's own on
// `email`, MediKube's on LOWER(email) — except `tokenKey`, which is fifty
// random characters nothing chooses. So a unique violation here is the address,
// and the alternative reading is a 500 on the ordinary case to avoid a 409 on
// an impossible one.
func writeFailure(doing string, err error) error {
	if strings.Contains(strings.ToLower(err.Error()), "unique constraint failed") {
		return fmt.Errorf("identity: %s: that address already has an account: %w", doing, domain.ErrConflict)
	}

	return fmt.Errorf("identity: %s: %w", doing, err)
}
